### ISSUE TITLE
Introduction of the function.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryoDocuments#6]
# Requirement
Upload to youtube the video after recording the steps of the tutorial of automatic generation. 
And you do the promotion for the user of the English-speaking world.
You give the Japanese and English subtitles to the each **3** videos.

## It has the purpose of promotion.
To promote the usability of the function along the tutorial.

### Target:
- [Tutorial_DPQ_analytical_tool_EN.doc](https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/master/documents/2_Tutorial/en/Tutorial_DPQ_analytical_tool_EN.doc)
- [Tutorial_Automatic_Screen_Generation(TableMaintenance)_EN.doc](https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/master/documents/2_Tutorial/en/Tutorial_Automatic_Screen_Generation(TableMaintenance)_EN.doc)
      
## It is intended to teach how to use.
To perform a description of how to use along the tutorial.

### Target:
- [Tutorial_ASPNET_C#_EN.doc](https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/master/documents/2_Tutorial/en/Tutorial_ASPNET_C%23_EN.doc)

# About tools
## Premise
- Free tool
- To recordings using the Windows
- Use the Youtube recommended encoding.  
https://support.google.com/youtube/answer/1722171?hl=ja
  - Container   : MP4
  - Audio codec : AAC-LC
  - Video codec : H.264

## Tool that is used
Since followings is provided free of charge from Microsoft,
such as license purchase is not required.

- Microsoft Expression Encoder 4  
https://www.microsoft.com/ja-jp/download/details.aspx?id=18974
- Windows Movie Maker (Shipped with Windows Essencials)  
http://windows.microsoft.com/ja-jp/windows-live/movie-maker

## Procedures
- To capture the operation by the "Microsoft Expression Encoder 4 Screen Capture".
- And, to export to WMV format by the "Microsoft Expression Encoder 4".
- And, to edit video by the "Windows Movie Maker", 
  - Insert subtitles.
  - Cut unnecessary part
  - , etc.

## Memo
- Video editing is possible by "Microsoft Expression Encoder 4", but, it seems a high degree of difficulty compared with "Windows Movie Maker". I think that is since difficult, maybe can edit elaborate.
- The default encoding of "Microsoft Expression Encoder 4" is WMV format. To output in the MP4 format, need the full version (paid) it is.

**Comment by SandeepNayak077** [comment]
Dear Nishino-san,

The recording video with audio and editing movie and adding subtitles is taking time.
Beceuse,
- we are practicing to create video. 
- Contacting technical team to include good quality of audio, during explation.
- Creating script document, containg both English and Japanese scripts.  

In this sprint we may complete the creation of the follwing tutorial video:
- Tutorial_DPQ_analytical_tool_EN.doc

Creation of following tutorial may take in the next sprint:
- Tutorial_Automatic_Screen_Generation(TableMaintenance)_EN.doc
- Tutorial_ASPNET_C#_EN.doc

Please confirm and let us know, is there any deadline to this task?

**Comment by daisukenishino** [comment]
There is no deadline.
Please consume the required time.
However, please report the estimates of consumption time required.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Thank you for the confirmation.
Estimated time is reported in the sprint plan.
Consumed time will be reported in the delivary mail.

**Comment by daisukenishino** [comment]
# Scope creep
We want to create a video of promotion and procedures separately for different purposes.

### How to use (procedures)
Operation description and a simple function description in compliance with each tutorials.

- Tutorial_ASPNET_C#_EN.doc
- Tutorial_DPQ_analytical_tool_EN.doc
- Tutorial_Automatic_Screen_Generation(TableMaintenance)_EN.doc

It is because there is a need to explain the operability and user friendliness and usability of this framework to user in pre-sales.

### promotion
Create one promotion video to end within five minutes that is not dependent on a specific tutorial.

# Conditions of start
### How to use (procedures)
This will use VS2015 and root_VS2015.
In addition, following correspondence need have been completed.

- Improvement of the build system (Nuget)  
https://github.com/OpenTouryoProject/OpenTouryo/issues/119
- The debug of "ProjectX_sample" in "root_VS2013" fails.  
https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/12

### promotion
Currentlly, there is a challenges to budget and how to proceed.
We can start this after measures is clarified.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

As discussed in the call today (07-July-16),
The **voice over** in the tutorial video is **not required**. 
Only **subtitles** (English and Japanese) is enough to understand the tutorial video.

**Reason:** Modification of tutorial video is difficult because more man hours required to,
- Create voice over for the video that match with existing audio frequency and quality.
- Sync new voice over with the existing video.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

I confirmed https://github.com/OpenTouryoProject/OpenTouryoDocuments/issues/6#issuecomment-231712819.
This is correct.

##### Note:
Please be increased the length of the time of scenes in proportion to the length of words.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> [/OpenTouryoTemplates/ - root_VS2015/Readme.md](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2015/Readme.md)
> Setup by Readme.md, and execute the sample.

As of now for root_VS2015, the ASP.NET website project is not merged to web application project.
So, this may impact end of the video **(Running the program)**.

Do I need to replace those video clips once the merge activity is completed?
Please confirm.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

I see.

@yusukemaegawa 

What should we do.

**Comment by yusukemaegawa** [comment]
@SandeepNayak077 
@daisukenishino 

If web service projects will be converted to *web application project* in the future, it is necessary to replace the video clips.
But, in this video, which demonstrates how to setup Open Touryo, I think the procedures to be related to web service are unnecessary.

Tomorrow, I will send the clips which I added comment to.

**Comment by daisukenishino** [comment]
# Change of scope 2
Since the man-hour is insufficient, we change the scope.

### Continue
Please continue to create the following high priority two videos.

- [/OpenTouryoTemplates/ - root_VS2015/Readme.md](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2015/Readme.md)  
Setup by Readme.md, and execute the sample.
- [Tutorial_DPQ_analytical_tool_EN.doc](https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/master/documents/2_Tutorial/en/Tutorial_DPQ_analytical_tool_EN.doc)  
To promote the usability of the function along the tutorial.

### Discontinue
Discontinue to create the following low priority two videos.

- [Tutorial_ASPNET_C#_EN.doc](https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/master/documents/2_Tutorial/en/Tutorial_ASPNET_C%23_EN.doc)  
To guide the performanceof the tutorial.
- [Tutorial_Automatic_Screen_Generation(TableMaintenance)_EN.doc](https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/master/documents/2_Tutorial/en/Tutorial_Automatic_Screen_Generation(TableMaintenance)_EN.doc)  
To promote the usability of the function along the tutorial.
