### ISSUE TITLE
Update the tutorial (Tutorial_SPA_C#_EN.doc)

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryoDocuments#9]
# Requirement
Because the quality of the [Tutorial_SPA_C#_EN.doc](https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/master/documents/2_Tutorial/en/Tutorial_SPA_C%23_EN.doc) is very low, I ask to create again this. Because the quality of recent research document have been improving, we are looking forward to this enhancement.

# Gap in perception of quality
There is a gap in perception of quality. I think that this quality gap can be understood by comparing the following two versions of [Tutorial_MVC_C#_EN.doc](https://github.com/OpenTouryoProject/OpenTouryoDocuments/commits/master/documents/2_Tutorial/en/Tutorial_MVC_C%23_EN.doc).

- [I has updated the following two documents. - 0afeba6  on 27 Mar 2015](https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/0afeba67364f4de784fa3e280ea41201ef14c1ed/documents/2_Tutorial/en/Tutorial_MVC_C%23_EN.doc)
- [Documentation Updates. - 5caf0d1  on 9 Oct 2014](https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/5caf0d188d42f6a91a3107eb84176bb12b8e240a/documents/2_Tutorial/en/Tutorial_MVC_C%23_EN.doc)

It should be awared that the quality of the first SPA tutorial is lower than compared with the quality of the first MVC tutorial. And, Document formatting should be compliant with the MVC tutorial.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

We have found the following two URLs, which explains about **S**ingle **P**age **A**pplication in English similar to the Japanese URL ([Single_Page_Application_jp](https://blogs.msdn.microsoft.com/chack/2012/05/17/single-page-application/)).
- [Single_Page_Application_en1](http://www.asp.net/single-page-application/overview/introduction/knockoutjs-template)
- [Single_Page_Application_en2](https://blogs.msdn.microsoft.com/webdev/2012/12/19/mvc-single-page-application-template-update-for-asp-net-and-web-tools-2012-2-rc/)

Please review and confirm the URL to be updated in [Tutorial_SPA_C#_EN.doc](https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/master/documents/2_Tutorial/en/Tutorial_SPA_C%23_EN.doc).

**Comment by daisukenishino** [comment]
@yusukemaegawa 

>- [Single_Page_Application_en1](http://www.asp.net/single-page-application/overview/introduction/knockoutjs-template)
- [Single_Page_Application_en2](https://blogs.msdn.microsoft.com/webdev/2012/12/19/mvc-single-page-application-template-update-for-asp-net-and-web-tools-2012-2-rc/)

Choose the appropriate URL as SPA explanation from the above.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

I found the following homepage:
[Single_Page_Application_en3](https://msdn.microsoft.com/en-us/magazine/dn463786.aspx)

This homepage explains the following:
- The Traditional Page Lifecycle vs. the SPA Lifecycle
- System development procedure with Visual Studio
- MVC pattern ant MVVM pattern
- Data Binding with knockout
- and so on

Therefore, I think that this homepage is easier to understand.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

We have updated the Table Of Contents (TOC) of SPA document is as follows:
```
Objective of this document
Scope of this document
Overview of this document
Use of copyrights and trademarks of other companies
1. Overview of Touryo
2. Environmental setting
2.1. Setup of Visual Studio Express 2012 for Web
2.2. Setup of Open Touryo template / base
2.3. DB Setup
3. Exercises in this tutorial
4. Exercises
4.1. Starting Visual Web Developer (VWD)
4.2. Generation of D layer
4.2.1. Auto Generation of D layer using DaoGen_Tool
4.2.2. Generation of SQL files
4.3. Add D Layer (Dao logic) to the application
4.3.1. Add Auto Generated Classes to the application
4.3.2. Add Dao Summary Class to the application
4.4. Add B Layer to the application
4.5. Add Parameter Class/Return Value Class (Screen code class) to the application
4.5.1. Add Parameter Class
4.5.2. Add Return Value Class
4.6. Add Models to the application
4.7. Add Controllers to the application
4.7.1. Add Controller For KnockOutJS
4.7.2. Add Controller For AngularJS
4.8. Add controllers to the application.
4.8.1. Add the controller For KnockOutJS.
4.8.2. Add the ccontroller for AngularJS
4.9. Add Views to the application.
4.9.1. Add the View For KnockOutJS.
4.9.2. Add the View For AngularJS
4.1. Add Styles to View pages
5. Behaviour Confirmation
5.1. For KnockOutJS
5.1.1. Display Order List, Order Details and Order Summary information
5.1.2. Updating Order Details and Order Summary information
5.1.3. Confirmation of data access using Log files
5.2. For AngularJS
5.2.1. Display Order List,Order Details and Order Summary information
5.2.2. Updating Order Details and Order Summary information
5.2.3. Confirmation of data access using Log files
```
↓↓↓
```
1. Overview of Touryo
2. Environmental setting
2.1. Setup of Visual Studio Express 2012 for Web
2.2. Setup of Open Touryo template / base
2.3. DB Setup
3. Exercises in this tutorial
4. Exercises
4.1. Starting Visual Web Developer (VWD)
4.2. Creating D layer (DAO logic class) to the application
4.2.1.  Auto generation of D layer (DAO logic class) and SQL files
4.2.2.  Arranging SQL files
4.2.3.  Adding Auto Generated D Layer (DAO logic class)
4.2.4.  Creating Dao Summary Class
4.3.  Creating B Layer (Business logic class) to the application
4.4.  Creating business entities to the application
4.4.6.  Creating Parameter class
4.4.7.  Creating Return Value class
4.5. Creating MVC and MVVM components to the application
4.5.1.  Creating Model (Web API)
4.5.2.  Creating Controller
4.5.3.  Creating View-Model
4.5.4.  Creating View (Screen)
5. Operation confirmation of the application
5.1. Starting ASP.NET service
5.2. Displaying Order List, Order Details and Order Summary information
5.3. Updating Order Details and Order Summary information
5.4. Confirming trace log
```

#### Removed TOC:
```
Objective of this document
Scope of this document
Overview of this document
Use of copyrights and trademarks of other companies
4.7.1. Add Controller For KnockOutJS
4.7.2. Add Controller For AngularJS
4.8. Add controllers to the application.
4.8.1. Add the controller For KnockOutJS.
4.8.2. Add the ccontroller for AngularJS
4.9.1. Add the View For KnockOutJS.
4.9.2. Add the View For AngularJS
4.1. Add Styles to View pages
5.1. For KnockOutJS
5.2. For AngularJS
5.2.1. Display Order List,Order Details and Order Summary information
5.2.2. Updating Order Details and Order Summary information
5.2.3. Confirmation of data access using Log files
```
#### Newly added TOC:
```
4.5.3.  Creating View-Model
5.1. Starting ASP.NET service
```

Please let us know, if there is any modification required.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>https://github.com/OpenTouryoProject/OpenTouryoDocuments/issues/9#issuecomment-234937526

Please use following page.

- ASP.NET - Single-Page Applications: Build Modern, Responsive Web Apps with ASP.NET 
https://msdn.microsoft.com/en-us/magazine/dn463786.aspx

>https://github.com/OpenTouryoProject/OpenTouryoDocuments/issues/9#issuecomment-235427124

There is no problem about the table of contents.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryoDocuments/issues/9#issuecomment-236521139

Thank you for the confirmation.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

The document is completed and it has been shared through IPS.
We have slightly modified the TOC as below
```TXT
1. Overview of Open Touryo framework
2. Environmental Setting
2.1  Setup of Visual Studio Express 2012 for Web
2.2  Setup of Open Touryo template-base
2.3  DB setup
3. Exercises in this tutorial
4. Exercises
4.1  Starting Visual Web Developer (VWD)
4.2  Creating business entities to the application
4.2.1  Creating Parameter Value class
4.2.2  Creating Return Value class
4.3  Creating D layer (DAO logic class) to the application
4.3.1  Auto generation of D layer (DAO logic class) and SQL files
4.3.2  Arranging sql files
4.3.3  Adding Auto Generated D Layer (DAO logic class)
4.3.4  Creating Dao Summary Class
4.3.5  Creating SQL file for the List of Orders
4.4  Creating B Layer (Business logic class) to the application
4.5  Creating MVC and MVVM components to the application
4.5.1  Creating Model (Web API)
4.5.2  Creating Controller
4.5.3  Creating ViewModel
4.5.4  Creating View (Screen)
5. Operation confirmation of the application
5.1  Starting ASP.NET service
5.2  Displaying Order List, Order Summary and Order Details information
5.3  Updating Order Summary and Order Details information
5.4  Confirming trace log
```

### Modification: ###
1. We have moved the section **4.4 Creating business entities to the application** to **4.2**, to show the accessibility of business entities in the DAO and Business logic class.
2. We have added new section **4.3.5  Creating SQL file for the List of Orders**.

Please confirm.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

There is no problem.
Please update the document by pullrequest.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryoDocuments/issues/9#issuecomment-248492736

We have updated document and created the [PullRequest#1](https://github.com/SymphonyTeleca/OpenTouryoDocuments/pull/1).
Please review and let us know.
